[package]
name = "rewav"
version = "0.1.0"
edition = "2024"

[dependencies]
infer = "0.13"

hound = "3.5"

flac = "0.2"

rubato = "0.15"

thiserror = "1.0"

log = "0.4"
env_logger = "0.11"

claxon = "0.4.3"

clap = { version = "4.5", features = ["derive"] }

num_cpus = "1.16"

rayon = "1.8"